parameters:
  atoolo_runtime_check.worker_status_file: '%kernel.cache_dir%/schedule_check.json'
  ## The period in minutes after which the worker status file is updated.
  atoolo_runtime_check.worker_status_update_period: 10

services:

  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Atoolo\Runtime\Check\Service\FastCgiStatusFactory:
    arguments:
        - [
          '/var/run/php-fpm.sock',
          '/var/run/php/php-fpm.sock',
          '/var/run/php*.sock',
          '/var/run/php/*.sock'
        ]
        - '%kernel.project_dir%/public/index.php'

  Atoolo\Runtime\Check\Service\ProcessStatus: ~

  Atoolo\Runtime\Check\Service\CliStatus:
    arguments:
      - '%kernel.project_dir%/bin/console'

  Atoolo\Runtime\Check\Service\WorkerStatusFile:
    arguments:
      - '%atoolo_runtime_check.worker_status_file%'
      - '%atoolo_runtime_check.worker_status_update_period%'

  Atoolo\Runtime\Check\Service\WorkerCheckScheduler:
    arguments:
      - '@Atoolo\Runtime\Check\Service\WorkerStatusFile'
      - '@Atoolo\Runtime\Check\Service\ProcessStatus'

  Atoolo\Runtime\Check\Console\Command\CheckCommand:
    arguments:
      - '@Atoolo\Runtime\Check\Service\FastCgiStatusFactory'
      - '@Atoolo\Runtime\Check\Service\WorkerStatusFile'
      - '@Atoolo\Runtime\Check\Service\ProcessStatus'

  Atoolo\Runtime\Check\Controller\CheckController:
    arguments:
      - '@Atoolo\Runtime\Check\Service\ProcessStatus'
      - '@Atoolo\Runtime\Check\Service\CliStatus'
